// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLV0BpymA4O_GFFBnVbsJTkAgKHlervAY',
    appId: '1:586648010047:web:00f6bffd517dc87e47e78a',
    messagingSenderId: '586648010047',
    projectId: 'fitness-life-calories',
    authDomain: 'fitness-life-calories.firebaseapp.com',
    storageBucket: 'fitness-life-calories.firebasestorage.app',
    measurementId: 'G-WV9MWJH80L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4d4k4D_7ZWVedl-1NTqQ2BvsndTRogF4',
    appId: '1:586648010047:android:dc22368dc5de199247e78a',
    messagingSenderId: '586648010047',
    projectId: 'fitness-life-calories',
    storageBucket: 'fitness-life-calories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA93xmXA1tuvciJZa2D-wQy4ycjDWT8s_4',
    appId: '1:586648010047:ios:a21790316da60a7347e78a',
    messagingSenderId: '586648010047',
    projectId: 'fitness-life-calories',
    storageBucket: 'fitness-life-calories.firebasestorage.app',
    iosBundleId: 'com.example.fitnessLifeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA93xmXA1tuvciJZa2D-wQy4ycjDWT8s_4',
    appId: '1:586648010047:ios:a21790316da60a7347e78a',
    messagingSenderId: '586648010047',
    projectId: 'fitness-life-calories',
    storageBucket: 'fitness-life-calories.firebasestorage.app',
    iosBundleId: 'com.example.fitnessLifeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLV0BpymA4O_GFFBnVbsJTkAgKHlervAY',
    appId: '1:586648010047:web:d08bb987b7d3733a47e78a',
    messagingSenderId: '586648010047',
    projectId: 'fitness-life-calories',
    authDomain: 'fitness-life-calories.firebaseapp.com',
    storageBucket: 'fitness-life-calories.firebasestorage.app',
    measurementId: 'G-BL8D6EXYY4',
  );
}
